### ISSUE TITLE
Question about selecting Model modes

### ISSUE THREAD

**Issue by stwcn1** [epri-dev/SCICHEM#13]
Hello,

Could you please explain the difference between the "reverse fast" and "fast" MODEL modes in the GUI?

When I select the "reverse fast" mode, the model fails to proceed and shows an error indicating that "error reading dos002 format surface file."

<img width="247" alt="2becee5da4e7c447317831a95af771f" src="https://github.com/user-attachments/assets/cd5a99f1-6f38-4b2d-a9f3-95e802e0858f">

**Comment by DougHenn1** [comment]
The "reverse" mode is not fully implemented in SCICHEM.  It is used for source term estimation and requires the meteorological input to run in reverse along with special input files.  But, as I said, it is not currently implemented.  (I should say not fully implemented since clearly there are remnants in the code, unfortunately.)
