### ISSUE TITLE
 No more puffs at Time

### ISSUE THREAD

**Issue by qingfengnanmeng** [epri-dev/SCICHEM#7]
During my 744-hour SCICHEM simulation, an unexpected interruption occurred at the 600-hour mark with the message ''No more puffs at Time = 697.8 hrs''.  Is this a normal occurrence, and what could be the underlying cause?
![d96535a6f6559db24cb7bcb15febb3e](https://github.com/epri-dev/SCICHEM/assets/127366298/bb379f54-f9b7-4b65-ac15-1231f922c6e1)

**Comment by DougHenn** [comment]
That means all of the puffs have been transported out of the computational domain.  SCICHEM will normally continue to run if there is an active source (which I assume is not the case since there apparently are no "new" puffs being created) or a source is set to start in the future. Otherwise, there is no reason to continue and SCICHEM stops.  Without knowing your specific source definitions, I would say this is probably normal behavior.

**Comment by DougHenn** [comment]
The duration of your release (TDUR) is 696 hours, so it seems plausible to me that there are no more puffs 1.8 hours later, depending on the size of the domain and wind speed.
